#!/usr/bin/python3

import sys

def factorize(number):
    factors = []
    for i in range(2, number + 1):
        while number % i == 0:
            factors.append(i)
            number //= i
            return factors

def main(tests/test00):
    try:
        with open(tests/test00, 'r') as file:
            for line in file:
                number = int(line.strip())
                factors = factorize(number)
                if len(factors) == 2:
                    p, q = factors
                    print(f"{number} = {p} * {q}")
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(tests/test00)
