#!/usr/bin/python3
import sys

def factorize(n):
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factors.append((i, n // i))
            return factors

def main(filename):
    with open(filename, "r") as file:
        for line in file:
            n = int(line)
            results = factorize(n)
            for factors in results:
                print(f"{n}={factors[0]}*{factors[1]}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filename = sys.argv[1]
    main(filename)

